root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/main ./cmd/app"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "templ", "html", "sql"]
exclude_ext = ["db"]
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
include_dir = []
exclude_regex = ["_test\\.go"]
follow_symlink = true

delay = 1000
kill_delay = "0.5s"
stop_on_error = true
send_interrupt = false

[log]
time = true
main_only = false

[screen]
clear_on_rebuild = true

[misc]
clean_on_exit = true
